{{- if .Values.operator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubefisher.operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubefisher.operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "kubefisher.operator.selectorLabels" . | nindent 4 }}
  ports:
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
      protocol: TCP
{{- end }}
