apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubefisher.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubefisher.costPatcher.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubefisher.costPatcher.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubefisher.costPatcher.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.gpuPricing.create }}
        checksum/configmap-gpu-pricing: {{ include (print $.Template.BasePath "/cost-patcher/configmap-gpu-pricing.yaml") . | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "kubefisher.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: cost-patcher
          image: {{ include "kubefisher.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - --prometheus-url={{ .Values.config.prometheusUrl }}
            - --pricing-namespace={{ .Release.Namespace }}
            - --pricing-configmap={{ .Values.gpuPricing.name }}
            - --pricing-key={{ .Values.gpuPricing.dataKey }}
            - --reconcile-interval={{ .Values.config.reconcileInterval }}
            - --pricing-refresh-interval={{ .Values.config.pricingRefreshInterval }}
            - --http-addr={{ .Values.config.httpAddr }}
            - --log-format={{ .Values.config.logFormat }}
          ports:
            - name: http-metrics
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
