{{- if .Values.observability.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kubefisher.fullname" . }}
  namespace: {{ include "kubefisher.namespaceOrDefault" (dict "ns" .Values.observability.serviceMonitor.namespace "ctx" .) }}
  labels:
    {{- include "kubefisher.costPatcher.labels" . | nindent 4 }}
    {{- with .Values.observability.serviceMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "kubefisher.costPatcher.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: {{ .Values.observability.serviceMonitor.interval }}
      {{- with .Values.observability.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
{{- end -}}
